### PR TITLE
Remove SNMP host based logic from DM

### PR DESCRIPTION
**Pull request by jinfanzon**
Since SNMP is containerized and no longer runs host-based,
then all SNMP related logic from DM has to be removed in
order to avoid errors.

Signed-off-by: Jose Infanzon <jose.infanzon@windriver.com>

### CODE REVIEW

**Review by donpenney — DISMISSED** [review]
lgtm

**Review by mwang3-wrs — COMMENTED** [review]
Is it possible to do a 'git commit --amend' to remove the [CGTS-22319] from the commit message?

**Comment by donpenney** [comment]
Why is there a revert of the "force flag" update now in this set?

**Comment by jinfanzon** [comment]
Due to a mistake, another commit was included in the PR. This commit was reverted, but for a better understanding, we created a new PR from scratch.

**Pull request closed without merging**
