### PR TITLE
StarlingX Field and URL updates

### PR DESCRIPTION
**Pull request by angtroake**
Update field names and URLs to match API reference and StarlingX system command.

**cpus:**
changed fields:
processor -> numa_node
logical_core -> cpu
physical_core -> core

**interfaceDataNetworks:**
added GET url and function
changed fields:
network_uuid -> datanetwork_uuid
network_id -> datanetwork_id

**storage tiers:**
updated resource url

### CODE REVIEW

**Review by donpenney — APPROVED** [review]
lgtm

**Comment by albailey** [comment]
Looks good to me.

**Comment by donpenney** [comment]
This fails the "vet" step:

$ go vet ./starlingx/...
# github.com/gophercloud/gophercloud/starlingx/inventory/v1/osds/testing [github.com/gophercloud/gophercloud/starlingx/inventory/v1/osds/testing.test]
starlingx/inventory/v1/osds/testing/requests_test.go:84:28: not enough arguments in call to osds.Create
        have (*gophercloud.ServiceClient, osds.OSDOpts)
        want (*gophercloud.ServiceClient, string, osds.OSDOpts)
# github.com/gophercloud/gophercloud/starlingx/inventory/v1/partitions/testing [github.com/gophercloud/gophercloud/starlingx/inventory/v1/partitions/testing.test]
starlingx/inventory/v1/partitions/testing/requests_test.go:79:34: not enough arguments in call to partitions.Create
        have (*gophercloud.ServiceClient, partitions.DiskPartitionOpts)
        want (*gophercloud.ServiceClient, string, partitions.DiskPartitionOpts)
# github.com/gophercloud/gophercloud/starlingx/inventory/v1/storagetiers/testing [github.com/gophercloud/gophercloud/starlingx/inventory/v1/storagetiers/testing.test]
starlingx/inventory/v1/storagetiers/testing/requests_test.go:21:26: too many arguments in call to storagetiers.List
        have (*gophercloud.ServiceClient, string, storagetiers.ListOpts)
        want (*gophercloud.ServiceClient, storagetiers.ListOptsBuilder)
starlingx/inventory/v1/storagetiers/testing/requests_test.go:49:36: too many arguments in call to storagetiers.List
        have (*gophercloud.ServiceClient, string, storagetiers.ListOpts)
        want (*gophercloud.ServiceClient, storagetiers.ListOptsBuilder)

**Comment by angtroake** [comment]
See #3

**Pull request closed without merging**
